### PR TITLE
Translate security-authorization-simple in Korean

### PR DESCRIPTION
**Pull request by gyuwon**
Improve the machine translated Korean content.

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C4%5C00079d8f-8a56-cb78-2c09-2e22a5f1a8bd%5CPullRequest%5C201712040222571948-19%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=a8%2FTIaAzH7slGlaod51BTZu%2FM213wp%2F93esqP%2FQwe9Q%3D&st=2017-12-04T02%3A18%3A00Z&se=2018-01-04T02%3A23%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gyuwon** [comment]
@v-tisip Could you explain what the validation error means?

**Comment by gosali** [comment]
Hi @gyuwon , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
@gyuwon , Thank you for your feedback and suggestion! 
  
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
  
Microsoft C&E Localization Team

**Pull request merged**
